events {}

http {
    server {
        listen 80;

        # Cabeçalhos globais repassados para todos os serviços (Frontend e Backend)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Backend (API, Admin, Swagger Docs, Healthcheck, Mídia e Arquivos Estáticos)
        location ~ ^/(api|admin|docs|health|media|static)($|/) {
            proxy_pass http://backend:8000;
        }

        # Frontend Next.js (Todas as outras rotas da aplicação)
        location / {
            proxy_pass http://frontend:3000;

            # Suporte ao Hot Reload (HMR/WebSockets) do Next.js
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
