# Generated by Django 6.1.1 on 2026-10-02 11:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onibus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=20, unique=True)),
                ('total_assentos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ônibus',
                'verbose_name_plural': 'Ônibus',
                'ordering': ('identificacao',),
            },
        ),
        migrations.CreateModel(
            name='Assento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('onibus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assentos', to='viagens.onibus')),
            ],
            options={
                'ordering': ('onibus', 'numero'),
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('CONVENCIONAL', 'Convencional'), ('EXECUTIVA', 'Executiva')], max_length=20)),
                ('partida_em', models.DateTimeField()),
                ('chegada_em', models.DateTimeField()),
                ('duracao', models.PositiveIntegerField(editable=False, help_text='Duração estimada em minutos.')),
                ('preco_centavos', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens_destino', to='viagens.cidade')),
                ('onibus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='viagens.onibus')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens_origem', to='viagens.cidade')),
            ],
            options={
                'verbose_name_plural': 'Viagens',
                'ordering': ('partida_em',),
            },
        ),
        migrations.CreateModel(
            name='ViagemAssento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('SEGURADO', 'Segurado'), ('RESERVADO', 'Reservado')], default='DISPONIVEL', max_length=20)),
                ('assento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagem_assentos', to='viagens.assento')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagem_assentos', to='viagens.viagem')),
            ],
            options={
                'verbose_name': 'Assento da viagem',
                'verbose_name_plural': 'Assentos das viagens',
                'ordering': ('viagem', 'assento__numero'),
            },
        ),
        migrations.AddConstraint(
            model_name='assento',
            constraint=models.UniqueConstraint(fields=('onibus', 'numero'), name='assento_numero_unico_por_onibus'),
        ),
        migrations.AddIndex(
            model_name='viagem',
            index=models.Index(fields=['origem', 'destino', 'partida_em'], name='viagem_busca_idx'),
        ),
        migrations.AddConstraint(
            model_name='viagem',
            constraint=models.CheckConstraint(condition=models.Q(('origem', models.F('destino')), _negated=True), name='viagem_origem_diferente_destino'),
        ),
        migrations.AddConstraint(
            model_name='viagem',
            constraint=models.CheckConstraint(condition=models.Q(('chegada_em__gt', models.F('partida_em'))), name='viagem_chegada_apos_partida'),
        ),
        migrations.AddConstraint(
            model_name='viagemassento',
            constraint=models.UniqueConstraint(fields=('viagem', 'assento'), name='viagem_assento_unico'),
        ),
    ]
