# Generated by Django 6.1.1 on 2026-10-04 04:19

import usuarios.models
import usuarios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(error_messages={'unique': 'Já existe um usuário com este e-mail.'}, max_length=254, unique=True)),
                ('password', models.CharField(db_column='senha_hash', max_length=128, verbose_name='senha')),
                ('celular', models.CharField(blank=True, max_length=11, validators=[usuarios.validators.validar_celular])),
                ('data_nasc', models.DateField(blank=True, null=True, validators=[usuarios.validators.validar_data_nascimento])),
                ('cpf', models.CharField(blank=True, error_messages={'unique': 'Já existe um usuário com este CPF.'}, max_length=11, null=True, unique=True, validators=[usuarios.validators.validar_cpf])),
                ('is_active', models.BooleanField(db_column='ativo', default=True, verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acesso ao admin')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ('nome',),
            },
            managers=[
                ('objects', usuarios.models.UsuarioManager()),
            ],
        ),
    ]
